# This file was generated by GoReleaser. DO NOT EDIT.
cask "jlo" do
  name "jlo"
  desc "TUI app for managing Jira issues and logging work hours"
  homepage "https://gitlab.com/balazs.hasprai/jlo"
  version "0.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jlo"

  on_macos do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_x86_64.tar.gz"
      sha256 "7e1e0f5c5b0b6e59389551d5c4e0ba84167ee70b443ae95ceba267633cf35e39"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_arm64.tar.gz"
      sha256 "8e24040ffe2ea09d8c9f7930ab2196666415a0905056cc1d70b1238d4a9ac0dd"
    end
  end

  on_linux do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_x86_64.tar.gz"
      sha256 "a4b07581d0236d0a00980c00825d194eb46166aad6beb512cd89567977bd54b7"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_arm64.tar.gz"
      sha256 "e8ab94f5c96553a6fbebc5589c16f10e56f9d66af144bdbd9ab12cb9c4ab2b63"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jlo"]
    end
  end

  # No zap stanza required
end
