# This file was generated by GoReleaser. DO NOT EDIT.
cask "jlo" do
  name "jlo"
  desc "TUI app for managing Jira issues and logging work hours"
  homepage "https://gitlab.com/balazs.hasprai/jlo"
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jlo"

  on_macos do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_x86_64.tar.gz"
      sha256 "be8d85e94dbcf51e3621b75969bbbbbaf087cee26d2c72f946cd8ab114379137"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_arm64.tar.gz"
      sha256 "f29a1f78926530715a07b108beb9a4369a0e44602006d1056ee5850d42aaf53b"
    end
  end

  on_linux do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_x86_64.tar.gz"
      sha256 "726e980cc4e391da1665beb64e911c1425f6ff425d9494167b4de9d6322d40e7"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_arm64.tar.gz"
      sha256 "900fe7a162bb4f77e4a69e12d4b8593152eda9a811783e5bc7a486e819f01383"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jlo"]
    end
  end

  # No zap stanza required
end
