# This file was generated by GoReleaser. DO NOT EDIT.
cask "jlo" do
  name "jlo"
  desc "TUI app for managing Jira issues and logging work hours"
  homepage "https://gitlab.com/balazs.hasprai/jlo"
  version "0.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jlo"

  on_macos do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_x86_64.tar.gz"
      sha256 "5ea608352c6c38853c8bc79f5df0122bef0b405813e41213efd311f68bbe18fb"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Darwin_arm64.tar.gz"
      sha256 "3359f6879a2e880c39b5056bf531675e912240548ef16eb9a0e96e1420848aad"
    end
  end

  on_linux do
    on_intel do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_x86_64.tar.gz"
      sha256 "437d7b6acc03af5b096f5d7fe261e6056b15a469fdf9c4aaf3dfcd789207f377"
    end
    on_arm do
      url "https://gitlab.com/balazs.hasprai/jlo/-/releases/#{version}/downloads/jlo_Linux_arm64.tar.gz"
      sha256 "2cb433b9151e5fc56199c7ae311cd4c405f316409b11ed60e8352c1c0a37b09e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jlo"]
    end
  end

  # No zap stanza required
end
